### ISSUE TITLE
Are the SDA and SCL pins exposed anywhere?

### ISSUE THREAD

**Issue by mikekberg** [sparkfun/Edison_9DOF_Block#1]
I'm trying to debug some communications issues with this block. Is there anywhere I can get a probe onto the SDA or SCL pins for this board?

**Comment by ShawnHymel** [comment]
SDA and SCL are the pads labeled "SDA" and "SCL" on the DATA and CLOCK 3-way solder jumpers. No real pins, but you can tack a couple of wires to the pads to connect to some probes.
